<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personne extends \App\Entity\Personne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'mail_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'mdp', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adherent', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'associations', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'structures', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adminAssos', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adminStructures', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'superAdmin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'intervenant'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'nom_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'prenom_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'mail_pers', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'mdp', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adherent', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'associations', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'structures', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adminAssos', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'adminStructures', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'superAdmin', '' . "\0" . 'App\\Entity\\Personne' . "\0" . 'intervenant'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Personne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPers(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPers', []);

        return parent::getNomPers();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPers(string $nom_pers): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPers', [$nom_pers]);

        return parent::setNomPers($nom_pers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomPers(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomPers', []);

        return parent::getPrenomPers();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomPers(string $prenom_pers): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomPers', [$prenom_pers]);

        return parent::setPrenomPers($prenom_pers);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailPers(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailPers', []);

        return parent::getMailPers();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailPers(string $mail_pers): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailPers', [$mail_pers]);

        return parent::setMailPers($mail_pers);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', []);

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp(string $mdp): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', [$mdp]);

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdherent(): ?\App\Entity\Adherent
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdherent', []);

        return parent::getAdherent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdherent(\App\Entity\Adherent $adherent): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdherent', [$adherent]);

        return parent::setAdherent($adherent);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssociations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssociations', []);

        return parent::getAssociations();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssociation(\App\Entity\Association $association): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssociation', [$association]);

        return parent::addAssociation($association);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssociation(\App\Entity\Association $association): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssociation', [$association]);

        return parent::removeAssociation($association);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructures', []);

        return parent::getStructures();
    }

    /**
     * {@inheritDoc}
     */
    public function addStructure(\App\Entity\Structure $structure): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStructure', [$structure]);

        return parent::addStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStructure(\App\Entity\Structure $structure): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStructure', [$structure]);

        return parent::removeStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminAssos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminAssos', []);

        return parent::getAdminAssos();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdminAsso(\App\Entity\AdminAsso $adminAsso): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdminAsso', [$adminAsso]);

        return parent::addAdminAsso($adminAsso);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdminAsso(\App\Entity\AdminAsso $adminAsso): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdminAsso', [$adminAsso]);

        return parent::removeAdminAsso($adminAsso);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminStructures(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminStructures', []);

        return parent::getAdminStructures();
    }

    /**
     * {@inheritDoc}
     */
    public function addAdminStructure(\App\Entity\AdminStructure $adminStructure): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAdminStructure', [$adminStructure]);

        return parent::addAdminStructure($adminStructure);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAdminStructure(\App\Entity\AdminStructure $adminStructure): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAdminStructure', [$adminStructure]);

        return parent::removeAdminStructure($adminStructure);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperAdmin(): ?\App\Entity\SuperAdmin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperAdmin', []);

        return parent::getSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin(\App\Entity\SuperAdmin $superAdmin): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', [$superAdmin]);

        return parent::setSuperAdmin($superAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervenant(): ?\App\Entity\Intervenant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervenant', []);

        return parent::getIntervenant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntervenant(\App\Entity\Intervenant $intervenant): \App\Entity\Personne
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntervenant', [$intervenant]);

        return parent::setIntervenant($intervenant);
    }

}
