<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFExyWO2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFExyWO2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFExyWO2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFExyWO2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFExyWO2\App_KernelDevDebugContainer([
    'container.build_hash' => 'FExyWO2',
    'container.build_id' => '67dcce57',
    'container.build_time' => 1591197743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFExyWO2');
